name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull latest code
        run: |
          cd /home/sl1n/PISTO-PORTAIL-TCGN
          git fetch origin
          git reset --hard origin/main
